### ISSUE TITLE
Crashing when using Nitrate

### ISSUE THREAD

**Issue by nijahplays** [terraria-catalyst/nitrate-mod#22]
Tested in latest version

[16:03:59.546] [Main Thread/FATAL] [tML]: Main engine crash

SDL Error: Unknown touch finger

Tip: This is likely a mod's fault. Disable mods one by one and check if the issue persists

System.InvalidOperationException: Begin has been called before calling End after the last call to Begin. Begin cannot be called again until End has been successfully called.
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect, Matrix transformMatrix) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\SpriteBatch.cs:line 284
   at Terraria.GameContent.AnOutlinedDrawRenderTargetContent.HandleUseReqest(GraphicsDevice device, SpriteBatch spriteBatch) in tModLoader\Terraria\GameContent\AnOutlinedDrawRenderTargetContent.cs:line 31
   at Terraria.Graphics.Renderers.MapHeadRenderer.PrepareRenderTarget(GraphicsDevice device, SpriteBatch spriteBatch) in tModLoader\Terraria\Graphics\Renderers\MapHeadRenderer.cs:line 72
   at DMD<System.Void Terraria.Main:DoDraw(Microsoft.Xna.Framework.GameTime)>(Main this, GameTime gameTime)
   at SyncProxy<System.Void Terraria.Main:DoDraw(Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
   at Terraria.Main.Draw_Inner(GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.RunLoop()
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.RunGame()
[16:03:59.546] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: shutdown

[client.log](https://github.com/terraria-catalyst/Nitrate/files/13799297/client.log)

**Comment by nijahplays** [comment]
Was able to confirm that it is Nitrate causing the crash, as without it this does not happen.

**Comment by nijahplays** [comment]
Also, the Discord link on your website is invalid
`https://discord.com/invite/vPTUZcvXjg`

**Comment by steviegt6** [comment]
Allegedly fixed in #28.
